services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Calien\SecureFilemount\:
    resource: '../Classes/*'
    exclude: '../Classes/ContextMenu/V11/*'

  Calien\SecureFilemount\EventListener\ModifyResourceIcon:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Core\Imaging\Event\ModifyIconForResourcePropertiesEvent

  Calien\SecureFilemount\EventListener\GeneratePublicUrlForSecureFilemount:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent

  Calien\SecureFilemount\EventListener\EditAccessRightsButton:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Backend\Template\Components\ModifyButtonBarEvent
